tap "argon/mas"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "rcmdnk/file"
tap "versent/taps"
brew "openssl@1.1"
brew "awscli"
brew "cloc"
brew "docker", link: false
brew "pcre2"
brew "fish"
brew "gettext"
brew "gh"
brew "git"
brew "icu4c"
brew "jq"
brew "nodenv"
brew "nvm"
brew "telnet"
brew "terraform-docs"
brew "terraform_landscape"
brew "tfenv"
brew "tree"
brew "yarn"
brew "argon/mas/mas"
brew "rcmdnk/file/brew-file"
brew "versent/taps/saml2aws"
cask "clipy"
cask "docker"
cask "intellij-idea"
cask "iterm2"
cask "karabiner-elements"
cask "kindle"
cask "sourcetree"
cask "visual-studio-code"
mas "Lightshot Screenshot", id: 526298438
mas "LINE", id: 539883307
mas "Monosnap", id: 540348655
